full_rebuild: true
name: ErgoDox Mechanical Keyboard 
description: Documentation and build guide for the ErgoDox mechanical keyboard
url: https://www.ergodox.io
encoding: utf-8
defaults:
  -
    values:
      layout: "index"
markdown: kramdown
kramdown:
  input: GFM
relative_permalinks: false
collections:
- entries
sass:
  sass_dir: _sass
  style: :compressed
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
exclude: [
.git,
.gitignore,
README.md,
.sass-cache
]
destination: ../deploy
